### ISSUE TITLE
Create model definition in Parse

### ISSUE THREAD

**Issue by wvega** [wvega/black-mamba#1]
The proposed models are:
### Brand
- id
- name
### Store
- id
- name
- location
### Item
- id
- name (Suavizante)
### Item Variation
- id
- item (ref)
- name
- description?
- brand (ref)
- store (ref)
- presentation_amount (weight, units)
- presentation_unit
- price

**Comment by dapanas** [comment]
Model done in Parse. Store's location is a GeoPoint.
