### ISSUE TITLE
Create ItemVariationPurchaseRow and/or ItemVariationPurchasesList

### ISSUE THREAD

**Issue by dapanas** [wvega/black-mamba#7]
Create components ItemVariationPurchaseRow and/or ItemVariationPurchasesList and update ItemVariationDetails component to use them.

**Comment by wvega** [comment]
Added in 91c4be116fa99e3. Closing.

**Comment by wvega** [comment]
Commit 91c4be116fa99e3 added an Item Variation Purchases List component. However, no Item Variation Purchase Row was created at this time, we may add that one later.
